### ISSUE TITLE
comment question

### ISSUE THREAD

**Issue by jinz2014** [ORNL/syclreduce#1]
Could you please explain the comment ?  Thanks.

"This is not called often by the library, but is an important part of the mathematics."

**Comment by frobnitzem** [comment]
That's explaining the importance of the identity operation in the README / example.

Every reduce has a "zero" and a "plus" operation, so it's important to be able to "return 0" when there's no list elements to reduce, or a thread needs to return an "empty" value.  For min/max, the zero value is the largest/smallest representable number.

It's not often called by the library because if the list size is one, the reduction returns a[0].  If greater, then the reduction starts with (a[0] + a[1], etc.).
